# Generated by Django 6.0.2 on 2026-02-22 12:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_list',
            name='session_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
