# Generated by Django 6.0.2 on 2026-02-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='fee_status',
            field=models.BooleanField(default=True),
        ),
    ]
