# Generated by Django 6.0.2 on 2026-02-10 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_attendance_fee_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_present', models.JSONField(default=list)),
                ('date_absent', models.JSONField(default=list)),
                ('fee_status', models.BooleanField(default=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.player')),
            ],
        ),
    ]
