# Generated by Django 6.0.2 on 2026-02-14 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_attendancestats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceStats',
        ),
    ]
