# Generated by Django 6.0.2 on 2026-02-14 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_attendancestats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
