# Generated by Django 6.0.2 on 2026-02-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_user_name_user_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendaceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('players_present', models.ManyToManyField(to='api.player')),
            ],
        ),
    ]
