# Generated by Django 6.0.2 on 2026-02-19 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_attendacesession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendaceSession',
        ),
    ]
